# Generated by Django 5.0.6 on 2024-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(null=True),
        ),
    ]
