# Generated by Django 5.0.6 on 2024-10-03 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_remove_task_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="list",
        ),
        migrations.DeleteModel(
            name="List",
        ),
    ]
